name: Continuous Delivery

on:
  push:
    branches: 
      - '*'

jobs:
  build:    
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetches entire history, so we can analyze commits since last tag
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Bump version and push tag
      id: set-version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore -l "console;verbosity=detailed"
    - name: Pack
      if: ${{ steps.set-version.outputs.new_version && github.ref == 'refs/heads/main' }}
      run: dotnet pack src/Spdy/Spdy.csproj -c Release -o nuget-packages --no-build -p:PackageVersion=${{ steps.set-version.outputs.new_version }} -p:PackageReleaseNotes="${{ steps.set-version.outputs.changelog }}"
    - name: Publish to nuget.org
      if: ${{ steps.set-version.outputs.new_version && github.ref == 'refs/heads/main' }}
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    outputs:
      version: ${{ steps.set-version.outputs.new_tag }}
      changelog: ${{ steps.set-version.outputs.changelog }}